on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_DEV_COLLECT_TELEMETRY: no
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install AZD
          uses: Azure/setup-azd@v0.1.0

        - name: Install .NET
          uses: actions/setup-dotnet@v3

        - name: Package Application
          run: azd package web --output-path ./dist/web.zip --environment NoEnvironment --no-prompt
          working-directory: ./

        - name: Upload website artifact (website)
          uses: actions/upload-artifact@v3
          with:
            name: package
            path: ./dist/web.zip
            if-no-files-found: error

  development:
    uses: ./.github/workflows/up.yml
    secrets: inherit
    needs: [build]
    with:
      AZURE_ENV_NAME: WebDev

  staging:
    uses: ./.github/workflows/up.yml
    secrets: inherit
    needs: [development]
    with:
      AZURE_ENV_NAME: WebStg

  production:
    uses: ./.github/workflows/up.yml
    secrets: inherit
    needs: [staging]
    with:
      AZURE_ENV_NAME: WebPrd